INFO  2024-09-14 10:30:14,755 crypto_virality_e2e_model.data:load_data_frame:59 - Loading Dataset[num_samples=None, random_seed=420, col_target=market_cap] from data\ml_data_set.csv
ERROR 2024-09-14 10:30:14,789 sensai.util.logging:run_main:112 - Exception during script execution
Traceback (most recent call last):
  File "C:\Users\haydn\PycharmProjects\crypto-virality-e2e-model\venv\Lib\site-packages\sensai\util\logging.py", line 108, in run_main
    result = main_fn()
             ^^^^^^^^^
  File "C:\Users\haydn\PycharmProjects\crypto-virality-e2e-model\run_model_evaluation.py", line 36, in main
    RegressionModelFactory.create_xgb()
  File "C:\Users\haydn\PycharmProjects\crypto-virality-e2e-model\crypto_virality_e2e_model\model_factory.py", line 74, in create_xgb
    fc = FeatureCollector(*cls.BASE_FEATURES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haydn\PycharmProjects\crypto-virality-e2e-model\venv\Lib\site-packages\sensai\featuregen\feature_generator_registry.py", line 97, in __init__
    self._multi_feature_generator = self.create_multi_feature_generator()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haydn\PycharmProjects\crypto-virality-e2e-model\venv\Lib\site-packages\sensai\featuregen\feature_generator_registry.py", line 134, in create_multi_feature_generator
    raise Exception(f"Received feature name '{f}' instead of instance but no registry to perform the lookup")
Exception: Received feature name 'FeatureName.NUMBER_PAGES' instead of instance but no registry to perform the lookup
